spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  jwt-secret: local-dummy-secret
  jwt-issuer: local-dummy-issuer
